version: '3'

tasks:
  up:
    desc: Start all services using Podman
    cmds:
      - podman-compose -f docker-compose.podman.yml down || true
      - podman-compose -f docker-compose.podman.yml up -d --build

  down:
    desc: Stop all services
    cmds:
      - podman-compose -f docker-compose.podman.yml down

  logs:
    desc: View logs
    cmds:
      - podman-compose -f docker-compose.podman.yml logs -f
  
  clean:
    desc: Stop services and remove persistent volumes (Fresh Start)
    cmds:
      - task: down
      - echo "Removing volumes..."
      - podman volume rm puente-poc_postgres_data || true
      - echo "System cleaned."

  start-infra:
    desc: Start blockchain and database only
    cmds:
      - podman-compose -f docker-compose.podman.yml up -d --build blockchain postgres
      - echo "Waiting for blockchain to be ready..."
      - sleep 5

  deploy-contracts:
    desc: Deploy contracts and update .env with new addresses
    cmds:
      - echo "Deploying contracts..."
      - |
        OUTPUT=$(podman exec -it puente-blockchain npx hardhat run scripts/deploy.ts --network localhost)
        echo "$OUTPUT"
        USDC=$(echo "$OUTPUT" | grep "USDC_ADDRESS=" | cut -d'=' -f2 | tr -d '\r')
        ESCROW=$(echo "$OUTPUT" | grep "ESCROW_ADDRESS=" | cut -d'=' -f2 | tr -d '\r')
        
        if [ -z "$USDC" ] || [ -z "$ESCROW" ]; then
          echo "Error: Failed to capture contract addresses."
          exit 1
        fi

        echo "Captured Addresses -> USDC: $USDC, ESCROW: $ESCROW"
        
        # Write to .env file for docker-compose to pick up
        echo "USDC_ADDRESS=$USDC" > .env
        echo "ESCROW_ADDRESS=$ESCROW" >> .env
        echo "Updated .env with new contract addresses."

  start-apps:
    desc: Start backend and frontend (requires .env from deploy)
    cmds:
      - podman-compose -f docker-compose.podman.yml up -d --build backend frontend

  setup:
    desc: Full setup with dynamic configuration
    cmds:
      - task: down
      - task: start-infra
      - task: deploy-contracts
      - task: start-apps
      - echo "Setup complete! Backend configured with latest contracts."
      - task: smoke-test

  smoke-test:
    desc: Run smoke tests inside the container network
    cmds:
      - |
        podman run --rm \
          --network puente-poc_puente-net \
          -v ./scripts:/scripts \
          node:20-slim \
          node /scripts/smoke-test.js

  test:
    desc: Run unit tests
    cmds:
      - cd backend && podman build -f Dockerfile.test -t puente-backend-test . && podman run --rm puente-backend-test

  test-contracts:
    desc: Run smart contract unit tests
    cmds:
      - echo "Running smart contract tests..."
      - podman exec -it puente-blockchain npx hardhat test
