/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace RemittanceEscrow {
  export type RemittanceStruct = {
    sender: AddressLike;
    recipientId: string;
    amountUSDC: BigNumberish;
    targetAmountCOP: BigNumberish;
    exchangeRate: BigNumberish;
    status: BigNumberish;
    createdAt: BigNumberish;
    fundedAt: BigNumberish;
    completedAt: BigNumberish;
  };

  export type RemittanceStructOutput = [
    sender: string,
    recipientId: string,
    amountUSDC: bigint,
    targetAmountCOP: bigint,
    exchangeRate: bigint,
    status: bigint,
    createdAt: bigint,
    fundedAt: bigint,
    completedAt: bigint
  ] & {
    sender: string;
    recipientId: string;
    amountUSDC: bigint;
    targetAmountCOP: bigint;
    exchangeRate: bigint;
    status: bigint;
    createdAt: bigint;
    fundedAt: bigint;
    completedAt: bigint;
  };
}

export interface RemittanceEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "REFUND_TIMEOUT"
      | "createRemittance"
      | "deposit"
      | "getContractBalance"
      | "getRemittance"
      | "getUserRemittances"
      | "owner"
      | "refund"
      | "release"
      | "remittanceCount"
      | "remittances"
      | "renounceOwnership"
      | "transferOwnership"
      | "usdc"
      | "userRemittances"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "RemittanceCompleted"
      | "RemittanceCreated"
      | "RemittanceFunded"
      | "RemittanceRefunded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "REFUND_TIMEOUT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createRemittance",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "deposit", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getContractBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRemittance",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserRemittances",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "refund", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "release", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "remittanceCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "remittances",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "userRemittances",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "REFUND_TIMEOUT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createRemittance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getContractBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRemittance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserRemittances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "refund", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "release", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "remittanceCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "remittances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "userRemittances",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RemittanceCompletedEvent {
  export type InputTuple = [remittanceId: BytesLike, timestamp: BigNumberish];
  export type OutputTuple = [remittanceId: string, timestamp: bigint];
  export interface OutputObject {
    remittanceId: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RemittanceCreatedEvent {
  export type InputTuple = [
    remittanceId: BytesLike,
    sender: AddressLike,
    recipientId: string,
    amountUSDC: BigNumberish,
    targetAmountCOP: BigNumberish,
    exchangeRate: BigNumberish
  ];
  export type OutputTuple = [
    remittanceId: string,
    sender: string,
    recipientId: string,
    amountUSDC: bigint,
    targetAmountCOP: bigint,
    exchangeRate: bigint
  ];
  export interface OutputObject {
    remittanceId: string;
    sender: string;
    recipientId: string;
    amountUSDC: bigint;
    targetAmountCOP: bigint;
    exchangeRate: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RemittanceFundedEvent {
  export type InputTuple = [remittanceId: BytesLike, timestamp: BigNumberish];
  export type OutputTuple = [remittanceId: string, timestamp: bigint];
  export interface OutputObject {
    remittanceId: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RemittanceRefundedEvent {
  export type InputTuple = [remittanceId: BytesLike, timestamp: BigNumberish];
  export type OutputTuple = [remittanceId: string, timestamp: bigint];
  export interface OutputObject {
    remittanceId: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RemittanceEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): RemittanceEscrow;
  waitForDeployment(): Promise<this>;

  interface: RemittanceEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  REFUND_TIMEOUT: TypedContractMethod<[], [bigint], "view">;

  createRemittance: TypedContractMethod<
    [recipientId: string, amountUSDC: BigNumberish, exchangeRate: BigNumberish],
    [string],
    "nonpayable"
  >;

  deposit: TypedContractMethod<[remittanceId: BytesLike], [void], "nonpayable">;

  getContractBalance: TypedContractMethod<[], [bigint], "view">;

  getRemittance: TypedContractMethod<
    [remittanceId: BytesLike],
    [RemittanceEscrow.RemittanceStructOutput],
    "view"
  >;

  getUserRemittances: TypedContractMethod<
    [user: AddressLike],
    [string[]],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  refund: TypedContractMethod<[remittanceId: BytesLike], [void], "nonpayable">;

  release: TypedContractMethod<[remittanceId: BytesLike], [void], "nonpayable">;

  remittanceCount: TypedContractMethod<[], [bigint], "view">;

  remittances: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        sender: string;
        recipientId: string;
        amountUSDC: bigint;
        targetAmountCOP: bigint;
        exchangeRate: bigint;
        status: bigint;
        createdAt: bigint;
        fundedAt: bigint;
        completedAt: bigint;
      }
    ],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  usdc: TypedContractMethod<[], [string], "view">;

  userRemittances: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "REFUND_TIMEOUT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "createRemittance"
  ): TypedContractMethod<
    [recipientId: string, amountUSDC: BigNumberish, exchangeRate: BigNumberish],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<[remittanceId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getContractBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRemittance"
  ): TypedContractMethod<
    [remittanceId: BytesLike],
    [RemittanceEscrow.RemittanceStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserRemittances"
  ): TypedContractMethod<[user: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "refund"
  ): TypedContractMethod<[remittanceId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "release"
  ): TypedContractMethod<[remittanceId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "remittanceCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "remittances"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        sender: string;
        recipientId: string;
        amountUSDC: bigint;
        targetAmountCOP: bigint;
        exchangeRate: bigint;
        status: bigint;
        createdAt: bigint;
        fundedAt: bigint;
        completedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "userRemittances"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RemittanceCompleted"
  ): TypedContractEvent<
    RemittanceCompletedEvent.InputTuple,
    RemittanceCompletedEvent.OutputTuple,
    RemittanceCompletedEvent.OutputObject
  >;
  getEvent(
    key: "RemittanceCreated"
  ): TypedContractEvent<
    RemittanceCreatedEvent.InputTuple,
    RemittanceCreatedEvent.OutputTuple,
    RemittanceCreatedEvent.OutputObject
  >;
  getEvent(
    key: "RemittanceFunded"
  ): TypedContractEvent<
    RemittanceFundedEvent.InputTuple,
    RemittanceFundedEvent.OutputTuple,
    RemittanceFundedEvent.OutputObject
  >;
  getEvent(
    key: "RemittanceRefunded"
  ): TypedContractEvent<
    RemittanceRefundedEvent.InputTuple,
    RemittanceRefundedEvent.OutputTuple,
    RemittanceRefundedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RemittanceCompleted(bytes32,uint256)": TypedContractEvent<
      RemittanceCompletedEvent.InputTuple,
      RemittanceCompletedEvent.OutputTuple,
      RemittanceCompletedEvent.OutputObject
    >;
    RemittanceCompleted: TypedContractEvent<
      RemittanceCompletedEvent.InputTuple,
      RemittanceCompletedEvent.OutputTuple,
      RemittanceCompletedEvent.OutputObject
    >;

    "RemittanceCreated(bytes32,address,string,uint256,uint256,uint256)": TypedContractEvent<
      RemittanceCreatedEvent.InputTuple,
      RemittanceCreatedEvent.OutputTuple,
      RemittanceCreatedEvent.OutputObject
    >;
    RemittanceCreated: TypedContractEvent<
      RemittanceCreatedEvent.InputTuple,
      RemittanceCreatedEvent.OutputTuple,
      RemittanceCreatedEvent.OutputObject
    >;

    "RemittanceFunded(bytes32,uint256)": TypedContractEvent<
      RemittanceFundedEvent.InputTuple,
      RemittanceFundedEvent.OutputTuple,
      RemittanceFundedEvent.OutputObject
    >;
    RemittanceFunded: TypedContractEvent<
      RemittanceFundedEvent.InputTuple,
      RemittanceFundedEvent.OutputTuple,
      RemittanceFundedEvent.OutputObject
    >;

    "RemittanceRefunded(bytes32,uint256)": TypedContractEvent<
      RemittanceRefundedEvent.InputTuple,
      RemittanceRefundedEvent.OutputTuple,
      RemittanceRefundedEvent.OutputObject
    >;
    RemittanceRefunded: TypedContractEvent<
      RemittanceRefundedEvent.InputTuple,
      RemittanceRefundedEvent.OutputTuple,
      RemittanceRefundedEvent.OutputObject
    >;
  };
}
